# Database credentials
database:
        db_name: "wiregost_db"
        db_user: "wiregost"
        db_password: "wiregost"

# Data service information
service:
        address: "localhost"
        port: 8001
        url: "/"
        certificate: "~/.wiregost/data-service/certs/wiregost_pub.pem"
        key: "~/.wiregost/data-service/certs/wiregost_priv_pem"
